version: 1.0.{build}
branches:
  only:
  - master
nuget:
  project_feed: true
before_build:
- ps: nuget restore ./CarSystem/CarSystem.sln
build:
  project: ./CarSystem/CarSystem.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
 # notifications:
 # - provider: Email
   # to:
   # - ooze89@yahoo.com
   # on_build_success: true
   # on_build_failure: true
   # on_build_status_changed: true
   
   
environment:
  COVERALLS_REPO_TOKEN:
    secure: X8MUeHD9WYL7QbtokIUW1ZfSRtic5m5i/672Ng3DbXch+YCc6TT58InYjIow91K2
    
    
after_test: 
        - CarSystem\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"CarSystem\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single CarSystem\Tests\CarSystem.Data.Tests\bin\Debug\CarSystem.Data.Tests.dll CarSystem\Tests\CarSystem.Data.Models.Tests\bin\Debug\CarSystem.Data.Models.Tests.dll " -output:cover.xml

        - CarSystem\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml