version: 1.0.{build}
branches:
  only:
  - master
nuget:
  project_feed: true
before_build:
- cmd: nuget restore ./CarSystem/CarSystem.sln
build:
  project: ./CarSystem/CarSystem.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
 # notifications:
 # - provider: Email
   # to:
   # - ooze89@yahoo.com
   # on_build_success: true
   # on_build_failure: true
   # on_build_status_changed: true
   
   
environment:
  COVERALLS_REPO_TOKEN:
    secure: 